Del *.uvgui.* /Q
Del *.uvguix.* /Q
Del *.uvgui_* /Q
Del *.bak /Q
Del "RTE\*.bak" /Q
Del "Source C Files\*.bak" /Q
Del "OP_Include\*.bak" /Q
Del "Objects\*.__i" /Q
Del "Objects\*.CRF" /Q
Del "Objects\*.D" /Q
Del "Objects\*.O" /Q
Del "Objects\*._ia" /Q
Del "Objects\*.axf" /Q
Del "Objects\*.DEP" /Q
Del "Objects\*.iex" /Q
Del "Objects\*.lnp" /Q
Del "OP_Include\*.tmp" /Q
Del "OP_Include\*.bak" /Q
Del "OP_Source\*.bak" /Q
